import React from 'react';
import './Terms.css';

function Terms() {
  return (
    <div className="terms-container">
      <h1 className="terms-title">Terms and Conditions</h1>
      <p className="terms-intro">
        This document (“Terms”) is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder, as applicable, and the amended provisions pertaining to electronic records in various statutes. It is generated by a computer system and does not require any physical or digital signatures.
      </p>
      <section className="terms-section">
        <h2>1. General</h2>
        <p>
          www.pharmeasy.in, an internet-based portal, and the “PharmEasy” mobile application (collectively referred to as the “Platform”), are operated by Axelia Solutions Private Limited (“Company” or “We” or “Us”). By accessing or using the Platform, You (“User” or “You”) agree to be bound by these Terms and Conditions, along with the Privacy Policy and other applicable policies.
        </p>
        <p>
          The Company reserves the right to modify these Terms at any time. Continued use of the Platform after such modifications constitutes Your acceptance of the updated Terms.
        </p>
      </section>
      <section className="terms-section">
        <h2>2. Products and Services</h2>
        <p>
          The Platform facilitates the purchase of pharmaceutical and wellness products, scheduling diagnostic tests, and consultations with registered medical practitioners. The Company acts as an intermediary and is not responsible for the authenticity or quality of the products or services provided by third-party vendors.
        </p>
      </section>
      <section className="terms-section">
        <h2>3. User Obligations</h2>
        <p>
          By using the Platform, You confirm that You are at least 18 years old and capable of entering into a legally binding contract. You agree to provide accurate and complete information during registration and to update such information as necessary.
        </p>
        <p>
          You shall not use the Platform for any unlawful purposes or in violation of these Terms. Any misuse of the Platform may result in termination of Your account and legal action.
        </p>
      </section>
      <section className="terms-section">
        <h2>4. Payment and Refunds</h2>
        <p>
          Payments for products and services can be made through various methods, including credit/debit cards, UPI, and net banking. Refunds, if applicable, will be processed in accordance with the Company’s Refund Policy.
        </p>
      </section>
      <section className="terms-section">
        <h2>5. Limitation of Liability</h2>
        <p>
          The Company shall not be liable for any direct, indirect, incidental, or consequential damages arising from the use of the Platform or the inability to use the Platform. The Company does not guarantee the accuracy or completeness of the information provided on the Platform.
        </p>
      </section>
      <section className="terms-section">
        <h2>6. Governing Law</h2>
        <p>
          These Terms shall be governed by and construed in accordance with the laws of India. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the courts in Mumbai, India.
        </p>
      </section>
      <section className="terms-section">
        <h2>7. Contact Us</h2>
        <p>
          If You have any questions or concerns regarding these Terms, please contact our grievance officer:
        </p>
        <p>
          Name: Mr. Himanshu<br />
          Address: Office No. E1-509, 5th Floor, Kailas Esplanade Premises Co-op Society Ltd, LBS Road, Ghatkopar West, Mumbai - 400086<br />
          Phone: 08048641743<br />
          Email: care@pharmeasy.in
        </p>
      </section>
    </div>
  );
}

export default Terms;